meta:
  environment: nodejs
  toolchain:
    name: npm
    version: 20

build:
  commands:
    - npm ci
    - npm run build

run:
  command: npm start
  persistenceMount: /data

configuration:
  runtime:
    port: 3000
    variables:
      NODE_ENV: production
